// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alasjbdyupzfoiugpszu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYXNqYmR5dXB6Zm9pdWdwc3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODYwOTYsImV4cCI6MjA2OTM2MjA5Nn0.4M50fEg62XR-g1juQmkvu_zJnZW-EXD6O-Ryoa4gDYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});